// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Cli.for_GeneratedContextVersion;

/// <summary>
/// The two generated files state their version differently - CHRONICLE.md in prose, the skill inside the
/// embedded descriptor - so either has to answer, or a stale catalog goes unnoticed in whichever file the
/// check happened to read.
/// </summary>
public class when_reading_the_generating_version : Specification
{
    [Fact] void should_read_it_from_the_chronicle_md_preamble() =>
        GeneratedContextVersion.ReadFrom("Generated by `cratis init` (CLI v2.8.2.0). Run `cratis init --refresh` to update.")
            .ShouldEqual("2.8.2.0");

    [Fact] void should_read_it_from_an_embedded_descriptor() =>
        GeneratedContextVersion.ReadFrom("""{ "tool": "cratis", "version": "2.9.0.0" }""")
            .ShouldEqual("2.9.0.0");

    [Fact] void should_answer_nothing_when_no_version_is_present() =>
        GeneratedContextVersion.ReadFrom("# Some hand written file").ShouldBeNull();

    [Fact] void should_answer_nothing_for_empty_content() =>
        GeneratedContextVersion.ReadFrom(string.Empty).ShouldBeNull();
}
