// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.Arc.Screenplay.Embedded.Generation;
using Cratis.Arc.Screenplay.Embedded.Hosting.Catalog;
using Cratis.Cli.Commands.Screenplay;

namespace Cratis.Cli.Commands.View;

/// <summary>
/// Generates the Screenplay documents of an application from its source, in memory.
/// </summary>
/// <remarks>
/// These are the documents the build would have embedded had the application referenced the embedded Screenplay
/// package - generated by the same Arc generator, one per assembly, module and feature - only held in memory and
/// served from there instead of being written anywhere.
/// </remarks>
public static class GeneratedEventModels
{
    /// <summary>
    /// Generates the documents of a project.
    /// </summary>
    /// <param name="projectFile">The full path of the project file.</param>
    /// <param name="output">What the project builds.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The resources holding the generated documents, and everything generating them reported.</returns>
    public static async Task<(IEventModelResources? Resources, IReadOnlyList<ViewDiagnostic> Diagnostics)> Generate(
        string projectFile,
        ProjectOutput output,
        CancellationToken cancellationToken)
    {
        var loaded = await ScreenplayCompilationLoader.Load(projectFile, string.IsNullOrWhiteSpace(output.TargetFramework) ? null : output.TargetFramework, cancellationToken);
        var diagnostics = loaded.Diagnostics.Select(ViewDiagnostic.From).ToList();
        if (loaded.Compilations.Count == 0)
        {
            return (null, diagnostics);
        }

        var generation = new EmbeddedDocumentGenerator().Generate(
            loaded.Compilations,
            new EmbeddedDocumentOptions(output.AssemblyName, output.RootNamespace));
        diagnostics.AddRange(generation.Diagnostics.Select(ViewDiagnostic.From));

        return generation.Documents.Count == 0
            ? (null, diagnostics)
            : (generation.ToResources(output.AssemblyName), diagnostics);
    }
}
