// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Completions;

/// <summary>
/// Generates a bash completion script for the Cratis CLI.
/// </summary>
public static class BashCompletionGenerator
{
    /// <summary>
    /// Generates the complete bash completion script.
    /// </summary>
    /// <returns>The bash completion script content.</returns>
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# bash completion for cratis")
            .AppendLine("# Generated by: cratis completions bash")
            .AppendLine()
            .AppendLine("_cratis() {")
            .AppendLine("    local cur prev words cword")
            .AppendLine("    _init_completion || return")
            .AppendLine()
            .AppendLine($"    local global_opts=\"{string.Join(' ', CliCommandTree.GlobalOptions)}\"")
            .AppendLine();

        var commands = CliCommandTree.Commands;
        var topLevelNames = string.Join(' ', commands.Select(c => c.Name));

        sb.AppendLine("    case \"${COMP_WORDS[1]}\" in");

        foreach (var cmd in commands)
        {
            if (cmd.Children.Count > 0)
            {
                GenerateBranch(sb, cmd, 1);
            }
            else
            {
                sb.AppendLine($"        {cmd.Name})")
                    .AppendLine($"            {CompReply(cmd)}")
                    .AppendLine("            return ;;");
            }
        }

        sb.AppendLine("    esac")
            .AppendLine()
            .AppendLine($"    COMPREPLY=( $(compgen -W \"{topLevelNames} $global_opts\" -- \"$cur\") )")
            .AppendLine("}")
            .AppendLine()
            .AppendLine("complete -F _cratis cratis");

        return sb.ToString();
    }

    static void GenerateBranch(StringBuilder sb, CommandNode node, int depth)
    {
        var childNames = string.Join(' ', node.Children.Select(c => c.Name));
        sb.AppendLine($"        {node.Name})")
            .AppendLine($"            case \"${{COMP_WORDS[{depth + 1}]}}\" in");

        foreach (var child in node.Children)
        {
            if (child.Children.Count > 0)
            {
                var grandChildNames = string.Join(' ', child.Children.Select(c => c.Name));
                sb.AppendLine($"                {child.Name})")
                    .AppendLine($"                    case \"${{COMP_WORDS[{depth + 2}]}}\" in");

                foreach (var grandChild in child.Children)
                {
                    sb.AppendLine($"                        {grandChild.Name})")
                        .AppendLine($"                            {CompReply(grandChild)}")
                        .AppendLine("                            return ;;");
                }

                sb.AppendLine("                    esac")
                    .AppendLine($"                    COMPREPLY=( $(compgen -W \"{grandChildNames} $global_opts\" -- \"$cur\") )")
                    .AppendLine("                    return ;;");
            }
            else
            {
                sb.AppendLine($"                {child.Name})")
                    .AppendLine($"                    {CompReply(child)}")
                    .AppendLine("                    return ;;");
            }
        }

        sb.AppendLine("            esac")
            .AppendLine($"            COMPREPLY=( $(compgen -W \"{childNames} $global_opts\" -- \"$cur\") )")
            .AppendLine("            return ;;");
    }

    static string CompReply(CommandNode node)
    {
        var opts = string.Join(' ', node.Options);
        if (node.DynamicCompletionContext is not null)
        {
            return $"COMPREPLY=( $(compgen -W \"$(cratis _complete {node.DynamicCompletionContext} 2>/dev/null) {opts} $global_opts\" -- \"$cur\") )";
        }

        return $"COMPREPLY=( $(compgen -W \"{opts} $global_opts\" -- \"$cur\") )";
    }
}
