// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Completions;

/// <summary>
/// Generates a fish completion script for the Cratis CLI.
/// </summary>
public static class FishCompletionGenerator
{
    /// <summary>
    /// Generates the complete fish completion script.
    /// </summary>
    /// <returns>The fish completion script content.</returns>
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# fish completion for cratis")
            .AppendLine("# Generated by: cratis completions fish")
            .AppendLine()
            .AppendLine("# Global options")
            .AppendLine("complete -c cratis -l server -d 'Chronicle server connection string' -r")
            .AppendLine("complete -c cratis -s o -l output -d 'Output format' -r -f -a 'json json-compact plain text'")
            .AppendLine("complete -c cratis -s q -l quiet -d 'Suppress non-essential output'")
            .AppendLine("complete -c cratis -s y -l yes -d 'Skip confirmation prompts'")
            .AppendLine("complete -c cratis -l management-port -d 'Management port' -r")
            .AppendLine();

        var commands = CliCommandTree.Commands;
        var topLevelNames = commands.Select(c => c.Name).ToArray();

        sb.AppendLine("# Disable file completions by default")
            .AppendLine("complete -c cratis -f")
            .AppendLine()
            .AppendLine("# Top-level commands");
        foreach (var cmd in commands)
        {
            var condition = NoSubcommandCondition(topLevelNames);
            sb.AppendLine($"complete -c cratis -n '{condition}' -a '{cmd.Name}' -d '{EscapeFish(cmd.Description)}'");
        }

        sb.AppendLine();

        foreach (var cmd in commands)
        {
            if (cmd.Children.Count > 0)
            {
                GenerateBranch(sb, cmd, [cmd.Name]);
            }
            else
            {
                GenerateOptions(sb, cmd, [cmd.Name]);
            }
        }

        return sb.ToString();
    }

    static void GenerateBranch(StringBuilder sb, CommandNode node, string[] parentPath)
    {
        var childNames = node.Children.Select(c => c.Name).ToArray();
        var pathCondition = SubcommandCondition(parentPath, childNames);

        sb.AppendLine($"# {string.Join(' ', parentPath)} subcommands");
        foreach (var child in node.Children)
        {
            sb.AppendLine($"complete -c cratis -n '{pathCondition}' -a '{child.Name}' -d '{EscapeFish(child.Description)}'");
        }

        sb.AppendLine();

        foreach (var child in node.Children)
        {
            string[] childPath = [.. parentPath, child.Name];
            if (child.Children.Count > 0)
            {
                GenerateBranch(sb, child, childPath);
            }
            else
            {
                GenerateOptions(sb, child, childPath);
            }
        }
    }

    static void GenerateOptions(StringBuilder sb, CommandNode node, string[] path)
    {
        if (node.Options.Count == 0)
        {
            return;
        }

        var condition = ContainsSubcommands(path);
        foreach (var opt in node.Options)
        {
            if (!opt.StartsWith('-'))
            {
                continue;
            }

            if (opt.StartsWith("--"))
            {
                var name = opt[2..];
                sb.AppendLine($"complete -c cratis -n '{condition}' -l '{name}' -d '{name}'");
            }
            else if (opt.StartsWith('-'))
            {
                var name = opt[1..];
                sb.AppendLine($"complete -c cratis -n '{condition}' -s '{name}' -d '{name}'");
            }
        }
    }

    static string NoSubcommandCondition(string[] knownCommands)
    {
        var commandList = string.Join(' ', knownCommands);
        return $"not __fish_seen_subcommand_from {commandList}";
    }

    static string SubcommandCondition(string[] parentPath, string[] childNames)
    {
        var parts = new List<string>();
        foreach (var segment in parentPath)
        {
            parts.Add($"__fish_seen_subcommand_from {segment}");
        }

        if (childNames.Length > 0)
        {
            parts.Add($"not __fish_seen_subcommand_from {string.Join(' ', childNames)}");
        }

        return string.Join("; and ", parts);
    }

    static string ContainsSubcommands(string[] path) =>
        string.Join("; and ", path.Select(s => $"__fish_seen_subcommand_from {s}"));

    static string EscapeFish(string text) => text.Replace("'", "\\'");
}
