// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Completions;

/// <summary>
/// Generates a PowerShell completion script for the Cratis CLI.
/// Compatible with both Windows PowerShell 5.1 and PowerShell 7+ (pwsh) on all platforms.
/// </summary>
public static class PowerShellCompletionGenerator
{
    /// <summary>
    /// Generates the complete PowerShell completion script.
    /// </summary>
    /// <returns>The PowerShell completion script content.</returns>
    public static string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("# PowerShell completion for cratis")
            .AppendLine("# Generated by: cratis completions powershell")
            .AppendLine("# Compatible with Windows PowerShell 5.1 and PowerShell 7+ (pwsh)")
            .AppendLine()
            .AppendLine("Register-ArgumentCompleter -Native -CommandName cratis -ScriptBlock {")
            .AppendLine("    param($wordToComplete, $commandAst, $cursorPosition)")
            .AppendLine()
            .AppendLine("    function Complete {")
            .AppendLine("        param([string[]] $candidates)")
            .AppendLine("        $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {")
            .AppendLine("            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    $words  = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.Value })")
            .AppendLine("    $n      = $words.Count")
            .AppendLine("    $depth  = $n - [int]($wordToComplete -ne '')")
            .AppendLine("    $prev   = if ($depth -gt 0) { $words[$depth - 1] } else { '' }")
            .AppendLine($"    $global = @({string.Join(", ", CliCommandTree.GlobalOptions.Select(Quoted))})");

        // Collect all option value completions across the whole tree (deduplicated by flag → context)
        var allOptionCompletions = CollectAllOptionCompletions(CliCommandTree.Commands);

        if (allOptionCompletions.Count > 0)
        {
            sb.AppendLine()
                .AppendLine("    # Option value completions — checked before command-tree navigation")
                .AppendLine("    switch -exact ($prev) {");

            // Group flags by their completion context so flags sharing a context are one case
            foreach (var group in allOptionCompletions.GroupBy(kv => kv.Value))
            {
                var flagList = group.Select(kv => Quoted(kv.Key)).ToArray();
                var condition = flagList.Length == 1
                    ? flagList[0]
                    : "{ $_ -in " + string.Join(", ", flagList) + " }";

                sb.AppendLine($"        {condition} {{ Complete @(cratis _complete {group.Key} 2>&1 | Where-Object {{ $_ -is [string] }}); return }}");
            }

            sb.AppendLine("    }");
        }

        // Command tree navigation via path string
        sb.AppendLine()
            .AppendLine("    $path = if ($depth -le 0) { '' } else { ($words[0..($depth - 1)]) -join '/' }")
            .AppendLine("    switch ($path) {");

        GeneratePathCases(sb, CliCommandTree.Commands);

        sb.AppendLine("        default { Complete $global }")
            .AppendLine("    }")
            .AppendLine("}");

        return sb.ToString();
    }

    static string Quoted(string s) => "'" + s + "'";

    static void GeneratePathCases(StringBuilder sb, IReadOnlyList<CommandNode> commands, string prefix = "")
    {
        // Root case: no command word typed yet
        if (string.IsNullOrEmpty(prefix))
        {
            var topLevel = string.Join(", ", commands.Select(c => Quoted(c.Name)));
            sb.AppendLine($"        '' {{ Complete (@({topLevel}) + $global) }}");
        }

        foreach (var cmd in commands)
        {
            var path = string.IsNullOrEmpty(prefix) ? cmd.Name : $"{prefix}/{cmd.Name}";

            if (cmd.Children.Count > 0)
            {
                var childNames = string.Join(", ", cmd.Children.Select(c => Quoted(c.Name)));
                sb.AppendLine($"        {Quoted(path)} {{ Complete (@({childNames}) + $global) }}");
                GeneratePathCases(sb, cmd.Children, path);
            }
            else
            {
                // Leaf: list its specific options
                var opts = cmd.Options.Where(o => o.StartsWith('-')).ToList();
                if (opts.Count == 0)
                {
                    sb.AppendLine($"        {Quoted(path)} {{ Complete $global }}");
                }
                else
                {
                    var optList = string.Join(", ", opts.Select(Quoted));
                    sb.AppendLine($"        {Quoted(path)} {{ Complete (@({optList}) + $global) }}");
                }
            }
        }
    }

    static Dictionary<string, string> CollectAllOptionCompletions(IReadOnlyList<CommandNode> commands)
    {
        var result = new Dictionary<string, string>();
        CollectRecursive(commands, result);
        return result;
    }

    static void CollectRecursive(IReadOnlyList<CommandNode> commands, Dictionary<string, string> result)
    {
        foreach (var cmd in commands)
        {
            foreach (var (flag, ctx) in cmd.OptionCompletions)
            {
                result.TryAdd(flag, ctx);
            }

            CollectRecursive(cmd.Children, result);
        }
    }
}
