// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Completions;

/// <summary>
/// Generates a zsh completion script for the Cratis CLI.
/// </summary>
public static class ZshCompletionGenerator
{
    /// <summary>
    /// Generates the complete zsh completion script.
    /// </summary>
    /// <returns>The zsh completion script content.</returns>
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("#compdef cratis")
            .AppendLine("# zsh completion for cratis")
            .AppendLine("# Generated by: cratis completions zsh")
            .AppendLine()
            .AppendLine("_cratis() {")
            .AppendLine("    local -a commands")
            .AppendLine("    local line state")
            .AppendLine()
            .AppendLine("    _arguments -C \\")
            .AppendLine("        '--server[Chronicle server connection string]:connection string:' \\")
            .AppendLine("        {-o,--output}'[Output format]:format:(json json-compact plain table)' \\")
            .AppendLine("        {-q,--quiet}'[Suppress non-essential output]' \\")
            .AppendLine("        {-y,--yes}'[Skip confirmation prompts]' \\")
            .AppendLine("        '--management-port[Management port]:port:' \\")
            .AppendLine("        '1: :->command' \\")
            .AppendLine("        '*::arg:->args'")
            .AppendLine()
            .AppendLine("    case $state in")
            .AppendLine("    command)")
            .AppendLine("        commands=(");

        var commands = CliCommandTree.Commands;
        foreach (var cmd in commands)
        {
            sb.AppendLine($"            '{cmd.Name}:{EscapeZsh(cmd.Description)}'");
        }

        sb.AppendLine("        )")
            .AppendLine("        _describe 'command' commands")
            .AppendLine("        ;;")
            .AppendLine("    args)")
            .AppendLine("        case $line[1] in");

        foreach (var cmd in commands)
        {
            if (cmd.Children.Count > 0)
            {
                sb.AppendLine($"        {cmd.Name})")
                    .AppendLine($"            _cratis_{cmd.Name.Replace('-', '_')}")
                    .AppendLine("            ;;");
            }
            else
            {
                sb.AppendLine($"        {cmd.Name})");
                GenerateLeafOptions(sb, cmd, "            ");
                sb.AppendLine("            ;;");
            }
        }

        sb.AppendLine("        esac")
            .AppendLine("        ;;")
            .AppendLine("    esac")
            .AppendLine("}")
            .AppendLine();

        foreach (var cmd in commands.Where(c => c.Children.Count > 0))
        {
            GenerateSubFunction(sb, $"_cratis_{cmd.Name.Replace('-', '_')}", cmd);
        }

        sb.AppendLine("compdef _cratis cratis");
        return sb.ToString();
    }

    static void GenerateSubFunction(StringBuilder sb, string funcName, CommandNode node)
    {
        sb.AppendLine($"{funcName}() {{")
            .AppendLine("    local -a subcommands")
            .AppendLine("    local line state")
            .AppendLine()
            .AppendLine("    _arguments -C \\")
            .AppendLine("        '1: :->subcommand' \\")
            .AppendLine("        '*::arg:->args'")
            .AppendLine()
            .AppendLine("    case $state in")
            .AppendLine("    subcommand)")
            .AppendLine("        subcommands=(");

        foreach (var child in node.Children)
        {
            sb.AppendLine($"            '{child.Name}:{EscapeZsh(child.Description)}'");
        }

        sb.AppendLine("        )")
            .AppendLine("        _describe 'subcommand' subcommands")
            .AppendLine("        ;;")
            .AppendLine("    args)")
            .AppendLine("        case $line[1] in");

        foreach (var child in node.Children)
        {
            if (child.Children.Count > 0)
            {
                sb.AppendLine($"        {child.Name})")
                    .AppendLine($"            {funcName}_{child.Name.Replace('-', '_')}")
                    .AppendLine("            ;;");
            }
            else
            {
                sb.AppendLine($"        {child.Name})");
                GenerateLeafOptions(sb, child, "            ");
                sb.AppendLine("            ;;");
            }
        }

        sb.AppendLine("        esac")
            .AppendLine("        ;;")
            .AppendLine("    esac")
            .AppendLine("}")
            .AppendLine();

        foreach (var child in node.Children.Where(c => c.Children.Count > 0))
        {
            GenerateSubFunction(sb, $"{funcName}_{child.Name.Replace('-', '_')}", child);
        }
    }

    static void GenerateLeafOptions(StringBuilder sb, CommandNode node, string indent)
    {
        var args = new List<string>();

        if (node.DynamicCompletionContext is not null)
        {
            args.Add($"'1: :($(cratis _complete {node.DynamicCompletionContext} 2>/dev/null))'");
        }

        foreach (var opt in node.Options)
        {
            if (!opt.StartsWith('-'))
            {
                continue;
            }

            args.Add($"'{opt}[{opt}]'");
        }

        if (args.Count == 0)
        {
            sb.AppendLine($"{indent}_arguments");
            return;
        }

        sb.AppendLine($"{indent}_arguments \\");

        for (var i = 0; i < args.Count; i++)
        {
            var trailing = i < args.Count - 1 ? " \\" : string.Empty;
            sb.AppendLine($"{indent}    {args[i]}{trailing}");
        }
    }

    static string EscapeZsh(string text) => text.Replace("'", "'\\''").Replace(":", "\\:");
}
