// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.Chronicle.Contracts.Clients;
using Cratis.Chronicle.Contracts.Observation;
using ProtoBuf.Grpc;

namespace Cratis.Cli.given;

/// <summary>
/// An <see cref="IObservers"/> that implements every member <b>explicitly</b>, forwarding to a substitute.
/// </summary>
/// <remarks>
/// <para>
/// This exists because of issue #185, and because the specification that was supposed to cover it could not fail.
/// The command looked its contract method up with <c language="csharp">Type.GetMethods()</c>, which does not return explicitly
/// implemented members - and the real client, generated by protobuf-net.Grpc, implements <see cref="IObservers"/>
/// explicitly. So the lookup found nothing and <c language="text">clear-quarantine</c> failed against every kernel
/// it was ever pointed at.
/// </para>
/// <para>
/// A plain <c language="csharp">Substitute.For&lt;IObservers&gt;()</c> would not have caught it: Castle's proxy implements the
/// interface <i>implicitly</i>, so reflection finds the method and the specification goes green while production
/// stays broken. That mismatch between the double and the real client is the whole defect, so specifications that
/// care about how the command reaches the contract use this instead - it is shaped like what actually ships.
/// </para>
/// </remarks>
/// <param name="inner">The substitute every call is forwarded to, for stubbing and verification.</param>
public sealed class an_observers_client_shaped_like_the_generated_proxy(IObservers inner) : IObservers
{
    /// <summary>
    /// Gets the substitute calls are forwarded to. Stub and assert against this.
    /// </summary>
    public IObservers Inner { get; } = inner;

    Task<ReplayResponse> IObservers.Replay(Replay command, CallContext context) => Inner.Replay(command, context);

    Task IObservers.ReplayPartition(ReplayPartition command, CallContext context) => Inner.ReplayPartition(command, context);

    Task<RetryPartitionResponse> IObservers.RetryPartition(RetryPartition command, CallContext context) => Inner.RetryPartition(command, context);

    Task IObservers.ClearObserverQuarantine(ClearObserverQuarantine command, CallContext context) => Inner.ClearObserverQuarantine(command, context);

    Task IObservers.ClearFailedPartitions(ClearFailedPartitions command, CallContext context) => Inner.ClearFailedPartitions(command, context);

    Task<RemoveObserverResponse> IObservers.RemoveObserver(RemoveObserver command, CallContext context) => Inner.RemoveObserver(command, context);

    Task<ObserverInformation> IObservers.GetObserverInformation(GetObserverInformationRequest request, CallContext context) => Inner.GetObserverInformation(request, context);

    Task<IEnumerable<ConnectedClient>> IObservers.GetConnectedClientsForObserver(GetConnectedClientsForObserverRequest request, CallContext context) => Inner.GetConnectedClientsForObserver(request, context);

    Task<IEnumerable<ObserverInformation>> IObservers.GetObservers(AllObserversRequest request, CallContext context) => Inner.GetObservers(request, context);

    IObservable<IEnumerable<ObserverInformation>> IObservers.ObserveObservers(AllObserversRequest request, CallContext context) => Inner.ObserveObservers(request, context);

    Task<WaitForObserverCompletionResponse> IObservers.WaitForCompletion(WaitForObserverCompletionRequest request, CallContext context) => Inner.WaitForCompletion(request, context);

    Task<IEnumerable<ObserverInformation>> IObservers.GetReplayableObserversForEventTypes(GetReplayableObserversForEventTypesRequest request, CallContext context) => Inner.GetReplayableObserversForEventTypes(request, context);
}
