// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Init;

/// <summary>
/// Generates the CHRONICLE.md reference document for AI agents.
/// </summary>
public static class ChronicleDocGenerator
{
    /// <summary>
    /// Generates the full CHRONICLE.md content.
    /// </summary>
    /// <returns>The document content as a string.</returns>
    public static string Generate()
    {
        var version = typeof(Program).Assembly.GetName().Version?.ToString() ?? "0.0.0";
        var sb = new StringBuilder();

        sb.AppendLine("# Chronicle CLI Reference")
            .AppendLine()
            .AppendLine($"Generated by `cratis init` (CLI v{version}). For the full machine-readable capability descriptor, run `cratis llm-context`.")
            .AppendLine()
            .AppendLine("## What is Chronicle?")
            .AppendLine()
            .AppendLine("Chronicle is an event-sourced system built by Cratis. It stores domain events in append-only event sequences,")
            .AppendLine("projects them into read models via observers (reactors, reducers, projections), and provides a gRPC API for management.")
            .AppendLine("The `cratis` CLI connects to a Chronicle server to inspect and manage event stores, observers, projections, and more.")
            .AppendLine()
            .AppendLine("## Connection Setup")
            .AppendLine()
            .AppendLine("The CLI resolves the server connection in this order:")
            .AppendLine("1. `--server` flag")
            .AppendLine("2. `CHRONICLE_CONNECTION_STRING` environment variable")
            .AppendLine("3. Active context in `~/.cratis/config.json`")
            .AppendLine("4. Default: `chronicle://localhost:35000`")
            .AppendLine()
            .AppendLine("```bash")
            .AppendLine("# Set up a named context")
            .AppendLine("cratis context create dev --server chronicle://localhost:35000/?disableTls=true")
            .AppendLine("cratis context set dev")
            .AppendLine("```")
            .AppendLine()
            .AppendLine("## Command Overview")
            .AppendLine()
            .AppendLine("| Command Group | Key Commands |")
            .AppendLine("|---|---|")
            .AppendLine("| `event-stores` | list |")
            .AppendLine("| `namespaces` | list |")
            .AppendLine("| `event-types` | list, show |")
            .AppendLine("| `events` | get, count (tail), has |")
            .AppendLine("| `observers` | list, show, replay, replay-partition, retry-partition |")
            .AppendLine("| `failed-partitions` | list, show |")
            .AppendLine("| `recommendations` | list, perform, ignore |")
            .AppendLine("| `identities` | list |")
            .AppendLine("| `projections` | list, show |")
            .AppendLine("| `read-models` | list, instances, get, occurrences, snapshots |")
            .AppendLine("| `auth` | status, login, logout |")
            .AppendLine("| `users` | list, add, remove |")
            .AppendLine("| `applications` | list, add, remove, rotate-secret |")
            .AppendLine("| `context` | list, create, set, show, delete, rename |")
            .AppendLine("| `config` | show, set, path |")
            .AppendLine("| (top-level) | version, update, llm-context, init |")
            .AppendLine()
            .AppendLine("## Global Flags")
            .AppendLine()
            .AppendLine("| Flag | Description |")
            .AppendLine("|---|---|")
            .AppendLine("| `--server <CONNECTION_STRING>` | Chronicle server connection string |")
            .AppendLine("| `-o, --output <FORMAT>` | Output format: json, text, plain, json-compact |")
            .AppendLine("| `-q, --quiet` | Output only key identifiers, one per line |")
            .AppendLine("| `-y, --yes` | Skip confirmation prompts |")
            .AppendLine("| `-e, --event-store <NAME>` | Event store name (default: default) |")
            .AppendLine("| `-n, --namespace <NAME>` | Namespace (default: Default) |")
            .AppendLine()
            .AppendLine("## Output Format Guidance")
            .AppendLine()
            .AppendLine("- Use `--output plain` for list commands (up to 34x fewer tokens than JSON).")
            .AppendLine("- Use `--output json-compact` when you need structured data with fewer tokens than `json`.")
            .AppendLine("- Use `--quiet` to get only IDs for piping: `cratis observers list -q | xargs -I {} cratis observers replay {} -y`")
            .AppendLine("- JSON errors include a machine-parseable `error` code alongside the `message`.")
            .AppendLine()
            .AppendLine("## Troubleshooting Decision Tree")
            .AppendLine()
            .AppendLine("### Cannot connect to server")
            .AppendLine("1. Run `cratis version -o json` — check if server version appears.")
            .AppendLine("2. Check connection string: `cratis config show -o json`.")
            .AppendLine("3. Verify server is running and reachable on the configured port.")
            .AppendLine()
            .AppendLine("### Observer stuck or behind")
            .AppendLine("1. Run `cratis observers list -o plain` — check observer state and sequence numbers.")
            .AppendLine("2. Run `cratis observers show <id> -o json` — inspect detailed state.")
            .AppendLine("3. Check failed partitions: `cratis failed-partitions list -o plain`.")
            .AppendLine("4. If a partition is failing, inspect: `cratis failed-partitions show <observer-id> <partition>`.")
            .AppendLine("5. Fix the underlying issue, then retry: `cratis observers retry-partition <observer-id> <partition> -y`.")
            .AppendLine("6. To replay from scratch: `cratis observers replay <observer-id> -y`.")
            .AppendLine()
            .AppendLine("### Data not appearing in read model")
            .AppendLine("1. Verify events exist: `cratis events has <event-source-id>`.")
            .AppendLine("2. Check the projection observer is running: `cratis observers list --type projection -o plain`.")
            .AppendLine("3. Check read model instances: `cratis read-models instances <name>`.")
            .AppendLine("4. Check for failed partitions on the projection observer.")
            .AppendLine()
            .AppendLine("## Safety Notes")
            .AppendLine()
            .AppendLine("- Replay and retry commands are destructive (they re-process events). Always confirm before running.")
            .AppendLine("- Use `--yes` only in automation with proper safeguards.")
            .AppendLine("- Remove commands (users, applications) are irreversible.")
            .AppendLine()
            .AppendLine("## Further Reading")
            .AppendLine()
            .AppendLine("- Full machine-readable descriptor: `cratis llm-context`")
            .AppendLine("- CLI version and compatibility: `cratis version -o json`");

        return sb.ToString();
    }
}
