// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text.RegularExpressions;

namespace Cratis.Cli.Commands.Init;

/// <summary>
/// Reads the CLI version that generated the files <c>cratis init</c> wrote, so a stale snapshot can be
/// reported rather than silently believed.
/// </summary>
/// <remarks>
/// The command catalog embedded in <c>CHRONICLE.md</c> and the generated skill is a snapshot taken when
/// <c>cratis init</c> ran, not something resolved live. After a CLI upgrade it keeps describing the older
/// surface: commands that have since been added are invisible to an agent, and ones that were renamed or
/// removed are still advertised. Nothing in the file says it is out of date, so the failure is silent and
/// an agent confidently writes a command that no longer exists.
/// </remarks>
public static partial class GeneratedContextVersion
{
    /// <summary>
    /// The version reported when a generated file carries no recognizable version at all.
    /// </summary>
    public const string Unknown = "unknown";

    [GeneratedRegex(@"CLI v(?<version>[0-9]+(?:\.[0-9]+)+)", RegexOptions.ExplicitCapture, 1000)]
    private static partial Regex ProseVersion { get; }

    [GeneratedRegex(@"""version""\s*:\s*""(?<version>[0-9]+(?:\.[0-9]+)+)""", RegexOptions.ExplicitCapture, 1000)]
    private static partial Regex DescriptorVersion { get; }

    /// <summary>
    /// Reads the generating CLI version out of the content of a file <c>cratis init</c> produced.
    /// </summary>
    /// <param name="content">The file content to read.</param>
    /// <returns>The version string, or <see langword="null"/> when the content carries none.</returns>
    public static string? ReadFrom(string content)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return null;
        }

        // CHRONICLE.md states it in prose ("CLI v2.8.2.0"); the skill carries it inside the embedded
        // descriptor ("version": "2.8.2.0"). Both are matched so either file can answer.
        var prose = ProseVersion.Match(content);
        if (prose.Success)
        {
            return prose.Groups["version"].Value;
        }

        var json = DescriptorVersion.Match(content);
        return json.Success ? json.Groups["version"].Value : null;
    }

    /// <summary>
    /// Decides whether a generated file is stale relative to the running CLI.
    /// </summary>
    /// <param name="generatedWith">The version read from the file, or <see langword="null"/> when absent.</param>
    /// <param name="running">The version of the running CLI.</param>
    /// <returns><see langword="true"/> when the file was generated by a different version.</returns>
    /// <remarks>
    /// A file carrying no version is deliberately <em>not</em> reported as stale. It predates version
    /// stamping or was hand-written, and warning about something the user cannot act on teaches them to
    /// ignore the warning - which costs more than the case it catches.
    /// </remarks>
    public static bool IsStale(string? generatedWith, string running) =>
        !string.IsNullOrWhiteSpace(generatedWith) &&
        !string.Equals(generatedWith, running, StringComparison.Ordinal);
}
